### ISSUE TITLE
Schematics and Gerber/Layout Files

### ISSUE THREAD

**Issue by hmelder** [e-radionicacom/Inkplate-6PLUS-Hardware#1]
Hi,
Thank you for designing a refined version of the Inkplate hardware.
The Inkplate 6 Plus is marketed as an OSH compliant product but I was not able to find the schematics and layout files.
It would be nice to have them aswell.

Best Regards

Hugo Melder

**Comment by davidzovko** [comment]
Hi Hugo, just [added](https://github.com/e-radionicacom/Inkplate-6PLUS-Hardware/commit/5059d883c2a7ebd4e57609ba5fb4a4fa1fa918e5), please check!
