### ISSUE TITLE
Is there an f3d file for this case?

### ISSUE THREAD

**Issue by clydebarrow** [e-radionicacom/Inkplate-6PLUS-Hardware#3]
It is provided for the original Inkplate 6, but not for the plus.

**Comment by davidzovko** [comment]
Added with https://github.com/e-radionicacom/Inkplate-6PLUS-Hardware/commit/e534992d60d3f1a4e5385466133c81a321928030 :)

**Comment by clydebarrow** [comment]
Thanks. I had already started doing my own, but the 3D model of the board came in useful (though it's missing the RTC battery and the display.)

My version attached. This is a snap-lock case - no screws.

![IMG_0054](https://user-images.githubusercontent.com/2366188/157439592-4b5b32ef-a628-4518-bd3f-696db0fe5587.JPG)
![Inkplate 6+ case v19 base](https://user-images.githubusercontent.com/2366188/157439610-e28715cc-b200-4e2f-9567-d3bb922e2403.png)
![Inkplate 6+ case v19 cover](https://user-images.githubusercontent.com/2366188/157439614-2c92ada8-be43-4534-9132-6743bce8c2f0.png)

[Inkplate 6+ case v19.zip](https://github.com/e-radionicacom/Inkplate-6PLUS-Hardware/files/8214406/Inkplate.6%2B.case.v19.zip)

**Comment by davidzovko** [comment]
Thanks for that, if you want to, make a new folder in the 3D enclosure folder and make a Pull request, I'll add it to the repo

**Comment by clydebarrow** [comment]
Ok, will do.
