### ISSUE TITLE
specifications/pinouts for the eInk display?

### ISSUE THREAD

**Issue by claud9999** [e-radionicacom/Inkplate-6PLUS-Hardware#5]
Where I could find reference material for the eInk display?

Thanks for the schematics and I've been able to find good documentation on the various chips but not for the display itself.

**Comment by davidzovko** [comment]
Hi, you are looking for ED060XH7 part number for the e-paper display. Since a lot of stuff there is under the NDA, you need to google and see what you can find. We did the same. Good luck!
