### ISSUE TITLE
add pull-up resistor for GPIO36?

### ISSUE THREAD

**Issue by claud9999** [e-radionicacom/Inkplate-6PLUS-Hardware#6]
Per the ESP32 documentation,

_GPI: GPIO34-39 can only be set as input mode and do not have software-enabled pullup or pulldown functions._

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/gpio.html

I believe this is why I'm seeing unreliable behavior (for example, the `Inkplate_Basic_Touchscreen_Draw` demo code reports `Touchscreen init fail` on some boots) as the touchscreen as the GPIO is "floating". I'm not great with electronics design, I'm wondering if there's a simple way to solder a pull-up resistor onto some pads to always pull up GPIO36?

See also: https://github.com/e-radionicacom/Inkplate-Arduino-library/issues/153

**Comment by ifadiga** [comment]
Hello,

Inkplate 6PLUS already has a pull-up resistor on GPIO36 (On sheet 5 in the Wake-up button circuit). Maybe you have a problem with something else on your Inkplate. 

Try to reconnect the touch cable and see what happens. If you have problems after that, feel free to contact us.

**Comment by claud9999** [comment]
Thanks Ivan, I think much of my issue was my own bad Arduino coding style. Sometimes the touchscreen doesn't init properly (true even with examples provided) but a re-power seems to fix. The Inkplate Arduino code tries to set a pullup resistor so I wasn't sure.
